### ISSUE TITLE
where RazerBlade 15 2020 Base Model Monterey?

### ISSUE THREAD

**Issue by abodypa9** [MarioBozhikov/RazerBlade_15_2020_Hackintosh#1]
hello, sorry i need RazerBlade 15 2020 Base Model Monterey..

**Comment by MarioBozhikov** [comment]
Check it out now. And just to give you a point if by any chance you don't know. You will need a second SSD check for compatibility (mine is Samsung 980 Evo).

**Comment by abodypa9** [comment]
Yes man you are the best , thanks, i have same ssd.. everything work well? except gpu?

**Comment by MarioBozhikov** [comment]
Well for better performance on the wi-fi, bluetooth, and if you want to have an airdrop. The wifi card has to be changed as well. Personally, I haven't changed it and it works fine for me. GPUs aren't supported anymore so if u want to wire a second monitor DisplayLink technology is the only option. Hope I answered your questions. :)

**Comment by abodypa9** [comment]
thanks bro, But unfortunately, I think there is a problem with your efi , maybe there problem in config. every time I boot, these three messages show. 
ocs:  no schema for serialinit at 6 index, context <debug>!
ocs: no schema for allowNvramRest at 0 index, context<secruity>!
ocs: no schema for allowtogglesip at 2 index, context <security>!

**Comment by MarioBozhikov** [comment]
And it doesn't boot at all?

**Comment by MarioBozhikov** [comment]
You have to edit your config.plist you can dig further on the link here if you can't boot at all.
 https://dortania.github.io/OpenCore-Post-Install/universal/update.html#_2-mount-your-efi
